# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - datamodule: cifar.yaml
  - model: vit.yaml
  - paths: default.yaml
  - trainer: default.yaml
  - logger: many_loggers.yaml
  - callbacks: default.yaml
  - hydra: default.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

   # config for hyperparameter optimization
  - hparams_search: null

# task name, determines output directory path
task_name: "demo"

# simply provide checkpoint path to resume training
ckpt_path: ???

demo_ckpt_path: ${paths.root_dir}/model.script.pt